### PR TITLE
[1.X] feature/player

### PR DESCRIPTION
**Pull request by rmunate**
With this PR, I aim to add a player from the available list, which will open a pop-up containing the player. If the m3u is no longer available, an error alert will be shown indicating a lost signal. This is the only feature left to add. I hope we can include it. Thank you.

### CODE REVIEW

**Review by Pecaquito — APPROVED** [review]
Perfect

**Comment by BellezaEmporium** [comment]
@freearhey won't contest my decision to close this PR because this isn't the goal of the website at all. We are showing the database of channels that are available worldwide, not offering a way to watch channels. Note that not all referenced channels possess an available stream URL.

**Comment by freearhey** [comment]
By the way, to watch stream in browser you can simply install an extension like [Native HLS Playback](https://chromewebstore.google.com/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof) and watch any HLS-video in a separate tab.

**Comment by thomraider12** [comment]
That's an L took there. So you make available links, but you don't tell or have a function to watch them?

**Comment by BellezaEmporium** [comment]
Please read again what i've wrote. This website is for the TV channels *database* and it is not made for watching channels. You have plenty of other ways to watch your favorite channels (even iptv-org/awesome-iptv provides you with a series of available players).

**Pull request closed without merging**
